### ISSUE TITLE
Official RPMs at http://xrootd.web.cern.ch/xrootd ?

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd-scitokens#1]
Dear XRootD-SciTokens maintainers,

I wonder if it would be possible to get "official" RPMs also together with the vanilla XRootD RPMs at:
http://xrootd.web.cern.ch/xrootd
We'd love to enable SciToken (and other token) support on our instance and are currently using the "vanilla" XRootD packages, while readily built RPMs of `xrootd-scitokens` seem to be available only in OSG repositories. 

Since `scitokens-cpp` is available at least in EPEL 7 and EPEL 8, I believe all dependencies can be covered by EPEL.

**Comment by simonmichal** [comment]
If @djw8605 is OK with that, I can add xrootd-scitokens as a submodule to xrootd builds.

**Comment by djw8605** [comment]
I am very happy to have xrootd-scitokens as a submodule to xrootd.

**Comment by simonmichal** [comment]
@djw8605 : could you have a look at #2 (I think it's not very controversial ;-), it will make it possible to build `xrootd-scitokens` as a submodule of core xrootd.

**Comment by simonmichal** [comment]
@djw8605 : is there a reason why `libXrdAccSciTokens` is being installed in `LIB_INSTALL_DIR` and not in `CMAKE_INSTALL_LIBDIR`?
https://github.com/xrootd/xrootd-scitokens/blob/67d69c54ec7b587e544a8d1026db378950e9f8c9/CMakeLists.txt#L41-L43

**Comment by djw8605** [comment]
No reason I can think of.  why that directory was chosen, I'm not sure.  But I'm open to change it.

**Comment by simonmichal** [comment]
Thanks for merging the PR :-) 

it would be great if you could change it to `CMAKE_INSTALL_LIBDIR`, that's where all other xrootd libs and plugins are installed :-)

**Comment by djw8605** [comment]
Ok, pull request created, waiting on travis-ci tests: https://github.com/scitokens/xrootd-scitokens/pull/34

(I opened it in the scitokens org because it already has the travis tests setup)

**Comment by djw8605** [comment]
@simonmichal ok, updated to use `CMAKE_INSTALL_LIBDIR`

**Comment by simonmichal** [comment]
@djw8605 : thanks for updating the `CMake` file! 

I integrated `xrootd-scitokens` as a submodule in xrootd core and added it into our CI builds :-)

It turns out there's one last missing thing, we are building XRootD for latest Fedora platforms and with `-Wall -Wextra` options which makes the compiler very picky ;-) 

The CI builds are failing with following error:

```
/xrootd/src/XrdSciTokens/XrdSciTokens/vendor/inih/INIReader.h:163:12: error: 'char* strncpy(char*, const char*, size_t)' specified bound 50 equals destination size [-Werror=stringop-truncation]
     strncpy(dest, src, size);
```

I created a PR that fixes this problem: #3 for your consideration ;-)

**Comment by simonmichal** [comment]
I suppose with #3 merged we can now close this?

**Comment by djw8605** [comment]
Agreed.
