### ISSUE TITLE
Token with invalid audience should result in a 401 error, instead of a 403

### ISSUE THREAD

**Issue by andreaceccanti** [xrootd/xrootd-scitokens#10]
According to the [RFC](https://datatracker.ietf.org/doc/html/rfc8725#section-3.9), if the token audience validation fails, the token should be fully rejected, i.e., leading to a 401 HTTP response status, instead of the 403 that is returned currently.

**Comment by amadio** [comment]
If this is still a problem, please open a new issue in the main XRootD repository, where the scitokens plugin is being maintained. This repository is no longer active. Thank you!
