### ISSUE TITLE
Scope based authentication broken for storage.read

### ISSUE THREAD

**Issue by dciangot** [xrootd/xrootd-scitokens#5]
I have just tried the scitoken lib from osg repositories on both xrootd4 and xrootd5 server using xrootd-http, but in both cases I notice the following:

- the authz is correctly managed using the scope `storage.write: /cms` allowing to writesomething only on the indicated path
- otoh the read and list operation is always allowed, not considering at all the presence or absence of the `storage.read` scope

I have no clue of what was changed since some months ago when everything was working correctly, could you take a look? Or, maybe, am I missing some recent change in the configuration?

**Comment by djw8605** [comment]
Hi!  I'm a little confused by your description.

> the authz is correctly managed using the scope storage.read: /cms allowing to writesomething only on the indicated path

If it's only read scope, then write should not work?

I would have to look into XRootD ACL permissions, but I think you can read / list any file if you have any permission at all, `storage.read`, `storage.write`, or `storage.modify`.  In your case, did the token have any permissions for the path?

**Comment by dciangot** [comment]
ops, sorry... made a huge swap in terms :/

I edited the messages above accordingly.

Of course the storage.modify was the one that worked correctly, while the `storage.read: /cms` is completely ignored, allowing everyone to read with a simple valid token without the correct scope

**Comment by dciangot** [comment]
In particular with a token with this content (*) I can read and list everything in `/`.

(*)
```{
  "wlcg.ver": "1.0",
  "sub": "df777.......0f9ae5",
  "aud": "https://wlcg.cern.ch/jwt/v1/any",
  "nbf": 1605195248,
  "scope": "address phone openid offline_access profile email",
  "iss": "https://iam-escape.cloud.cnaf.infn.it/",
  "exp": 1605198848,
  "iat": 1605195248,
  "jti": "20559......a6509fc4",
  "client_id": "b4abd6d.....f68c7ba2"
}```

**Comment by djw8605** [comment]
What does your xrootd configuration look like?  Specifically, I am interested in the line specifying the scitokens library.  Are you using an auth file in xrootd?

What I suspect is happening is that scitokens is correctly denying access, then it is falling back to using the authfile, which may have some general "read" permission for the path.

**Comment by dciangot** [comment]
yes, this can be very likely, but should not be like that right? :/ Here the auth file (*) and the relevant part of the xrootd configuration (**) with the scitoken version "xrootd-scitokens.x86_64 0:1.2.2-1.osgup.el7". Also the scitoken.cfg here (***).

(*)
u xrootd / lr

(**)
```
if exec xrootd
xrd.port 31094
xrd.protocol XrdHttp:31094 libXrdHttp.so
fi

#http.trace
# Uncomment the following line to get extensive debugging information
http.trace all debug

# Enable the SciTokens authorization library.
ofs.authorize
ofs.authlib libXrdAccSciTokens.so config=/etc/xrootd/scitokens.cfg

# This particular authfile allows anonymous writes.
acc.authdb /etc/xrootd/Auth-file-http

http.header2cgi Authorization authz

# Boiler-plate HTTPS configuration
http.cadir /etc/grid-security/certificates
http.cert /etc/grid-security/hostcert.pem
http.key /etc/grid-security/hostcert.key

http.listingdeny yes
http.staticpreload http://static/robots.txt /etc/xrootd/robots.txt
```


(***)
```
[Issuer VOTest]
issuer = https://iam-escape.cloud.cnaf.infn.it/
base_path = /
map_subject = False
default_user = xrootd
```

**Comment by dciangot** [comment]
Ok, with a quick test, this looks like fixed by removing the `acc.authdb /etc/xrootd/Auth-file-http`

So probably was not inteded to work like that 2 months ago, and the fallback is indeed the way it means to work. Can you confirm this?

In any cases, I ok with that.

**Comment by djw8605** [comment]
We also use Authfiles in the OSG.  But we do not have a global "read" directive like you have.  I would suggest having a more restricted authfile.

Here is an example of a StashCache authenticated origin Authfile:
https://topology.opensciencegrid.org/stashcache/origin-authfile?fqdn=hcc-stashcache-origin.unl.edu

The `/hcc/PROTECTED` directory is protected by the either GSI or tokens.  XRootD will try tokens, then GSI authentication.

I'm going to close this issue, but feel free to reopen or reply.
