### ISSUE TITLE
error: ‘scitoken_get_claim_string_list’ was not declared in this scope

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd-scitokens#8]
On following platforms: fedora 32, fedora 33 and fedora rawhide the `scitoken_get_claim_string_list` does not exists, and the builds fail with following error:

/xrootd/src/XrdSciTokens/XrdSciTokens/src/XrdAccSciTokens.cc: In member function ‘bool XrdAccSciTokens::GenerateAcls(const string&, uint64_t&, {anonymous}::AccessRulesRaw&, std::string&, std::string&, std::string&, std::vector<{anonymous}::MapRule>&, std::vector<std::__cxx11::basic_string<char> >&)’:
/xrootd/src/XrdSciTokens/XrdSciTokens/src/XrdAccSciTokens.cc:585:14: error: ‘scitoken_get_claim_string_list’ was not declared in this scope; did you mean ‘scitoken_get_claim_string’?
  585 |         if (!scitoken_get_claim_string_list(token, "wlcg.groups", &group_list, &err_msg)) {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              scitoken_get_claim_string
/xrootd/src/XrdSciTokens/XrdSciTokens/src/XrdAccSciTokens.cc:589:13: error: ‘scitoken_free_string_list’ was not declared in this scope
  589 |             scitoken_free_string_list(group_list);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~

Could this be fixed before we release `5.1.0`?

**Comment by djw8605** [comment]
Interesting, I think the fedora releases have never been high priority, and have not kept up with the el7 and el8 release of scitokens-cpp.  I suspect it's a version issue, too old on those platforms.

I can update the scitokens-cpp package in fedora.  Hopefully it's just a matter of pushing a new build (which I do so infrequently, I have to relearn how to do it each time)

**Comment by djw8605** [comment]
I think this is fixed in the scitokens-cpp release https://bodhi.fedoraproject.org/updates/FEDORA-2020-185f4449f4
